---
- name: Create a file
  ansible.builtin.file:
    path: /home/ubuntu/file.txt
    state: touch
    mode: '0644'

- name: Add "hello" message to the file
  ansible.builtin.lineinfile:
    path: /home/ubuntu/file.txt
    line: "hello"
    create: yes